server:                  #配置server
  tomcat:       #springboot乱码解决
    uri-encoding: UTF-8
  port: 8094

spring:
  devtools:      #热部署
    restart:
      enabled: true
  http:       #springboot乱码解决
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
      name: zuul-server

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://localhost:8091/eureka/
  instance:
    instance-id: zuul-server-8094
    prefer-ip-address: true     #访问路径可以显示IP地址

zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-operation
    courseType:
      path: /courseType/**
      serviceId: main-operation
  host:
    socket-timeout-millis: 100000
    connect-timeout-millis: 10000

